---
# Setting up all hosts
- hosts: proxy:masters:workers
  tasks: [ ]

# Manual etc when we have more than 1 masters
- hosts: masters
  roles:
    - etcd

- hosts: proxy:masters:workers
  roles:
    - kubernetes

- hosts: proxy:masters:workers
  roles:
    - kubernetes-multimasters
